---
- name: Apply sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Remount swap maybe not needed
  ansible.builtin.debug:
    msg: "Swap entries commented in /etc/fstab (if any)."
