# Network interface used to set kubelet --node-ip
kubelet_node_ip_interface: "eth0"

# Kubernetes repo channel
kubernetes_major_minor: "v1.34" # maps to pkgs.k8s.io/core:/stable:/v1.34/deb/

# Package selector pattern used to pick exact version from apt-cache madison
kubernetes_madison_match: "1.34."

# crictl version (set the exact one you want)
crictl_version: "v1.30.0"

# Containerd settings
containerd_systemd_cgroup: true
