---
- name: Bootstrap all Kubernetes nodes (control-plane + workers)
  hosts: k8s_nodes
  become: true
  gather_facts: true

  roles:
    - role: k8s_prereqs
    - role: containerd
    - role: crictl
    - role: kubernetes_node
